### ISSUE TITLE
Patching Issue 

### ISSUE THREAD

**Issue by burramsettyarvind** [KLGLUG/Xenomai#2]
![error1](https://user-images.githubusercontent.com/26138737/32687263-891f4c20-c686-11e7-9d08-aefedb8f2baf.png)

> Unable to patch kernel 4.13.1 with ipipe-core-3.18.20-x86-7.patch.

**Comment by burramsettyarvind** [comment]
code model kernel doesnt support PIC mode
![error2](https://user-images.githubusercontent.com/26138737/32687971-be78afb0-c695-11e7-9ddf-97f2312a50bc.jpg)

**Comment by PoonamSalecha** [comment]
This error is because the version of kernel and ipipe does not match.The compiler couldnot interface both and give the result.Inorder to resolve this issue u need to either upgrade the ipipe version or downgrade the kernel version.
